service:
  telemetry:
    metrics:
      readers:
        - pull:
            exporter:
              prometheus:
                host: 127.0.0.1
                port: 8889
  extensions: [jaeger_storage, jaeger_query]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [jaeger_storage_exporter]

extensions:
  jaeger_query:
    storage:
      traces: memstore
    http:
      endpoint: 127.0.0.1:16686
  jaeger_storage:
    backends:
      memstore:
        memory:
          max_traces: 100000

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 127.0.0.1:4319
      http:
        endpoint: 127.0.0.1:4320

processors:
  batch:

exporters:
  jaeger_storage_exporter:
    trace_storage: memstore