management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics
          - gateway
          - prometheus
  endpoint:
    health:
      show-details: when_authorized
  health:
    defaults:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}