otel:
  enabled: false

management:
  opentelemetry:
    logging:
      export:
        otlp:
          endpoint: http://localhost:4318/v1/logs
        schedule-delay: 1s
    tracing:
      export:
        otlp:
          endpoint: http://localhost:4318/v1/traces
  otlp:
    metrics:
      export:
        url: http://localhost:4318/v1/metrics
        enabled: ${otel.enabled}
  tracing:
    sampling:
      probability: 1.0
    export:
      otlp:
        enabled: ${otel.enabled}